# 财报智析 Agent Demo

本 Notebook 展示从示例财务数据读取、数据清洗、指标计算、风险识别、杜邦分析到报告生成的完整流程。

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path('..').resolve()
sys.path.insert(0, str(PROJECT_ROOT))

from agents.main_agent import run_financial_analysis

excel_path = PROJECT_ROOT / 'data' / 'sample_financial_data.xlsx'
result = run_financial_analysis(excel_path, enable_pdf=False, report_level='标准版')
result.keys()

dict_keys(['options', 'model_config', 'raw_data', 'cleaned_data', 'missing_core_items', 'warnings', 'validation', 'ratio_results', 'ratio_pivot', 'trend_summary', 'dupont', 'cashflow', 'risks', 'charts', 'report', 'pdf_info', 'trace', 'trace_path', 'core_metrics'])

## 1. 标准化后的财务数据

In [2]:
result['cleaned_data']

                              2022      2023      2024
item
accounts_receivable        26000.0   41000.0   62000.0
asset_impairment_loss       1200.0    1800.0    3100.0
cash                       42000.0   39000.0   36000.0
cash_received_from_sales  130000.0  150000.0  158000.0
current_assets            150000.0  168000.0  186000.0
current_liabilities        76000.0   93000.0  112000.0
inventory                  38000.0   52000.0   76000.0
net_operating_cash_flow    16000.0   12500.0    9800.0
net_profit                 14500.0   17800.0   16600.0
non_recurring_pnl            900.0    1200.0    4200.0
operating_cost             72000.0   92000.0  108000.0
operating_revenue         120000.0  145000.0  162000.0
total_assets              310000.0  365000.0  430000.0
total_equity              182000.0  195000.0  205000.0
total_liabilities         128000.0  170000.0  225000.0

## 2. 指标计算结果

In [3]:
result['ratio_pivot']

,指标类别,指标名称,计算公式,指标含义,2022,2023,2024
0,偿债能力,权益乘数,总资产 / 所有者权益,衡量权益资本撬动资产规模的杠杆倍数。,1.70,1.87,2.10
1,偿债能力,流动比率,流动资产 / 流动负债,衡量企业短期偿债能力。,1.97,1.81,1.66
2,偿债能力,资产负债率,总负债 / 总资产,衡量企业财务杠杆水平。,41.29%,46.58%,52.33%
3,偿债能力,速动比率,(流动资产 - 存货) / 流动负债,剔除存货后衡量即时短期偿债能力。,1.47,1.25,0.98
4,成长能力,净利润增长率,(本年净利润 - 上年净利润) / 上年净利润,衡量利润成长速度。,,22.76%,-6.74%
5,成长能力,总资产增长率,(本年总资产 - 上年总资产) / 上年总资产,衡量资产规模扩张速度。,,17.74%,17.81%
6,成长能力,所有者权益增长率,(本年所有者权益 - 上年所有者权益) / 上年所有者权益,衡量权益资本积累速度。,,7.14%,5.13%
7,成长能力,营业收入增长率,(本年营业收入 - 上年营业收入) / 上年营业收入,衡量收入规模成长速度。,,20.83%,11.72%
8,现金流量质量,净利润现金含量,经营活动现金流量净额 / 净利润,衡量净利润由经营活动现金流量净额支撑的程度。,110.34%,70.22%,59.04%
9,现金流量质量,经营现金流量收入比率,经营活动现金流量净额 / 营业收入,衡量营业收入转化为经营活动现金流量净额的能力。,13.33%,8.62%,6.05%
10,现金流量质量,销售收现比率,销售商品、提供劳务收到的现金 / 营业收入,衡量收入回款质量。,108.33%,103.45%,97.53%
11,盈利能力,净利率,净利润 / 营业收入,衡量收入转化为最终利润的能力。,12.08%,12.28%,10.25%
12,盈利能力,净资产收益率（ROE）,净利润 / 平均所有者权益,衡量股东投入资本形成净利润的能力。,7.97%,9.44%,8.30%
13,盈利能力,总资产报酬率（ROA）,净利润 / 平均总资产,衡量总资产报酬水平。,4.68%,5.27%,4.18%
14,盈利能力,毛利率,(营业收入 - 营业成本) / 营业收入,衡量产品或服务的基本盈利空间。,40.00%,36.55%,33.33%
15,营运能力,存货周转率,营业成本 / 平均存货,衡量存货周转和管理效率。,1.89,2.04,1.69
16,营运能力,应收账款周转率,营业收入 / 平均应收账款,衡量商业债权回收效率。,4.62,4.33,3.15
17,营运能力,总资产周转率,营业收入 / 平均总资产,衡量资产整体运营效率。,0.39,0.43,0.41

## 3. 趋势分析与风险识别

In [4]:
result['trend_summary'], result['risks']

(           分析对象 趋势判断                         主要依据  \
 0          营业收入   上升   2022 年至 2024 年累计变动 35.00%。
 1           净利润   波动   2022 年至 2024 年累计变动 14.48%。
 2    经营活动现金流量净额   下降  2022 年至 2024 年累计变动 -38.75%。
 3           总资产   上升   2022 年至 2024 年累计变动 38.71%。
 4           总负债   上升   2022 年至 2024 年累计变动 75.78%。
 5         所有者权益   上升   2022 年至 2024 年累计变动 12.64%。
 6          应收账款   上升  2022 年至 2024 年累计变动 138.46%。
 7            存货   上升  2022 年至 2024 年累计变动 100.00%。
 8           毛利率   下降  2022 年至 2024 年累计变动 -16.67%。
 9           净利率   波动  2022 年至 2024 年累计变动 -15.20%。
 10  净资产收益率（ROE）   波动    2022 年至 2024 年累计变动 4.18%。
 11        资产负债率   上升   2022 年至 2024 年累计变动 26.73%。
 12         流动比率   下降  2022 年至 2024 年累计变动 -15.86%。
 13      净利润现金含量   下降  2022 年至 2024 年累计变动 -46.50%。

                                  初步解释
 0    营业收入呈上升态势，需结合质量、现金流和战略背景判断其可持续性。
 1           净利润波动较明显，建议关注业务稳定性和一次性因素。
 2      经营活动现金流量净额呈下降态势，提示相关能力或规模可能承压。
 3     总资产呈上升态势，需结合质量、现金流和战略背景判断其可持续性。
 4     总负债呈上升态势，需结合质量、现金流和战略背景判断其可持续性。
 5   所有者权益呈上升态势，需结合质量、现金流和战略背景判断其可持续性。
 6    应收账款呈上升态势，需结合质量、现金流和战略背景判断其可持续性。
 7      存货呈上升态势，需结合质量、现金流和战略背景判断其可持续性。
 8             毛利率呈下降态势，提示相关能力或规模可能承压。
 9           净利率波动较明显，建议关注业务稳定性和一次性因素。
 10  净资产收益率（ROE）波动较明显，建议关注业务稳定性和一次性因素。
 11  资产负债率呈上升态势，需结合质量、现金流和战略背景判断其可持续性。
 12           流动比率呈下降态势，提示相关能力或规模可能承压。
 13        净利润现金含量呈下降态势，提示相关能力或规模可能承压。  ,
 [{'risk_id': 'R101',
   'risk_name': '应收账款增长异常',
   'risk_level': '中',
   'evidence': '2024 年应收账款增长率 51.22%，高于营业收入增长率 11.72%。',
   'explanation': '提示赊销规模或回款压力可能上升，收入质量需结合账龄结构进一步核查。',
   'suggestion': '关注客户信用政策、应收账款账龄和坏账准备计提充分性。'},
  {'risk_id': 'R102',
   'risk_name': '存货增长较快',
   'risk_level': '中',
   'evidence': '2024 年存货增长率 46.15%，高于营业成本增长率 17.39%。',
   'explanation': '提示存货周转和跌价压力可能增加。',
   'suggestion': '进一步核查存货库龄、产品结构和跌价准备计提情况。'},
  {'risk_id': 'R104',
   'risk_name': '毛利率连续下降',
   'risk_level': '中',
   'evidence': '毛利率近三年连续下降。',
   'explanation': '提示产品竞争力或成本控制可能承压。',
   'suggestion': '关注售价、原材料成本、产品结构和费用转嫁能力。'},
  {'risk_id': 'R105',
   'risk_name': '资产负债率持续上升',
   'risk_level': '中',
   'evidence': '资产负债率近三年持续上升。',
   'explanation': '提示偿债压力和财务弹性需关注。',
   'suggestion': '进一步区分金融性负债与经营性负债，并关注债务期限结构。'},
  {'risk_id': 'R106',
   'risk_name': '短期偿债能力下降',
   'risk_level': '中',
   'evidence': '2024 年流动比率和速动比率较上年同时下降。',
   'explanation': '提示短期偿债安全边际可能收窄。',
   'suggestion': '关注流动负债到期压力、受限资金和存货变现能力。'},
  {'risk_id': 'R107',
   'risk_name': '经营活动现金流量净额长期低于净利润',
   'risk_level': '高',
   'evidence': '净利润现金含量至少两个年度低于 100%。',
   'explanation': '提示盈余质量和利润现金含量需关注。',
   'suggestion': '结合商业信用、应收账款回款和存货占用进一步核查。'},
  {'risk_id': 'R109',
   'risk_name': '资产减值损失大幅增加',
   'risk_level': '中',
   'evidence': '2024 年资产减值相关项目增长 72.22%。',
   'explanation': '提示资产质量可能承压，需关注减值测试和相关资产可收回金额。',
   'suggestion': '进一步核查应收、存货、商誉和长期资产减值明细。'},
  {'risk_id': 'R110',
   'risk_name': '非经常性损益影响较大',
   'risk_level': '中',
   'evidence': '2024 年非经常性损益占净利润比例约 25.30%。',
   'explanation': '提示利润可持续性需关注。',
   'suggestion': '重点比较扣非净利润和经常性业务盈利能力。'}])

## 4. 杜邦分析

In [5]:
result['dupont']['dupont_table']

   year  net_margin  total_asset_turnover  equity_multiplier      roe
0  2022    0.120833              0.387097           1.703297  0.07967
1  2023    0.122759              0.429630           1.871795  0.09443
2  2024    0.102469              0.407547           2.097561  0.08300

## 5. 报告路径

In [6]:
result['report']['markdown_path'], result['report']['word_path'], result['trace_path']

(PosixPath('/Users/vison/Desktop/学习/大二下/生成式ai/期末作业/accounting-agent/outputs/reports/financial_analysis_report.md'),
 PosixPath('/Users/vison/Desktop/学习/大二下/生成式ai/期末作业/accounting-agent/outputs/reports/financial_analysis_report.docx'),
 PosixPath('/Users/vison/Desktop/学习/大二下/生成式ai/期末作业/accounting-agent/outputs/agent_trace.json'))